import { MonthlyReportData, ClientData } from './types';

export const INITIAL_CLIENTS: ClientData[] = [
  {
    id: 'client-bulungi-town',
    name: 'Bulungi Town',
    logoUrl: '/logos/bulungi-town.svg',
    createdAt: '2026-06-01T00:00:00Z',
    socialAccounts: [
      {
        id: 'sa-bulungi-ig',
        clientId: 'client-bulungi-town',
        platform: 'instagram',
        platformAccountId: 'ig_bulungitown_official',
        accessToken: 'mock_ig_access_token_60day',
        tokenExpiresAt: '2026-08-20T00:00:00Z',
      },
      {
        id: 'sa-bulungi-tt',
        clientId: 'client-bulungi-town',
        platform: 'tiktok',
        platformAccountId: 'tt_bulungitown_official',
        accessToken: 'mock_tt_access_token_365day',
        refreshToken: 'mock_tt_refresh_token',
        tokenExpiresAt: '2027-06-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'client-safi-bay',
    name: 'Safi Bay',
    logoUrl: '/logos/safi-bay.svg',
    createdAt: '2026-06-01T00:00:00Z',
    socialAccounts: [
      {
        id: 'sa-safi-ig',
        clientId: 'client-safi-bay',
        platform: 'instagram',
        platformAccountId: 'ig_safibay_official',
        accessToken: 'mock_ig_access_token_safibay',
        tokenExpiresAt: '2026-08-20T00:00:00Z',
      },
      {
        id: 'sa-safi-tt',
        clientId: 'client-safi-bay',
        platform: 'tiktok',
        platformAccountId: 'tt_safibay_official',
        accessToken: 'mock_tt_access_token_safibay',
        refreshToken: 'mock_tt_refresh_token_safibay',
        tokenExpiresAt: '2027-06-01T00:00:00Z',
      },
    ],
  },
];

export const INITIAL_REPORTS: Record<string, MonthlyReportData> = {
  'client-bulungi-town': {
    id: 'report-bulungi-june',
    clientId: 'client-bulungi-town',
    startDate: '2026-06-11',
    endDate: '2026-07-10',
    goals: [
      'Double down on the concepts which gave us initial results, continue to show the construction progress',
      'Introduce Hassan as the founder, setting up future storylines',
    ],
    insights: [
      'Additional video with our social media manager Ashley talking about the brand and what we are creating, that was posted on Koko digital page is sitting on 120k on TikTok.',
      'Interact with the audience more to create a strong connection between them and the brand.',
    ],
    nextSteps: [
      'Create content that involves the audience and brings them into the conversation.',
    ],
    igFollowersGrowth: 1100,
    igViews: 167000,
    igViewsPctChange: 3543.0,
    igEngagementRate: 4.5,
    ttFollowersGrowth: 2600,
    ttViews: 476800,
    ttViewsPctChange: 436.7,
    ttEngagementRate: 8.2,
    posts: [
      {
        id: 'post-b1',
        platform: 'tiktok',
        postId: 'tt_post_163k',
        contentFormat: 'Videos',
        viewsCount: 163200,
        likesCount: 12400,
        commentsCount: 385,
        sharesCount: 1654,
        thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: true,
        publishedAt: '2026-06-15T12:00:00Z',
      },
      {
        id: 'post-b2',
        platform: 'tiktok',
        postId: 'tt_post_118k',
        contentFormat: 'Videos',
        viewsCount: 118000,
        likesCount: 9200,
        commentsCount: 290,
        sharesCount: 899,
        thumbnailUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: true,
        publishedAt: '2026-06-19T14:30:00Z',
      },
      {
        id: 'post-b3',
        platform: 'instagram',
        postId: 'ig_post_87k',
        contentFormat: 'Videos',
        viewsCount: 87200,
        likesCount: 3395,
        commentsCount: 107,
        sharesCount: 1223,
        thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: true,
        publishedAt: '2026-06-25T16:00:00Z',
      },
      {
        id: 'post-b4',
        platform: 'instagram',
        postId: 'ig_post_graphic_1',
        contentFormat: 'Graphic',
        viewsCount: 15400,
        likesCount: 890,
        commentsCount: 42,
        sharesCount: 120,
        thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: false,
        publishedAt: '2026-06-20T10:00:00Z',
      },
      // Additional story/video entries for format breakdown metrics
      {
        id: 'post-b5',
        platform: 'instagram',
        postId: 'ig_stories_pack',
        contentFormat: 'Stories',
        viewsCount: 42000,
        likesCount: 1200,
        commentsCount: 45,
        sharesCount: 80,
        thumbnailUrl: null,
        isTopPerformer: false,
        publishedAt: '2026-07-01T10:00:00Z',
      },
    ],
  },
  'client-safi-bay': {
    id: 'report-safi-june',
    clientId: 'client-safi-bay',
    startDate: '2026-06-11',
    endDate: '2026-07-10',
    goals: [
      'Double down on concepts that gave us initial results, with a strong focus on announcing the opening and showcasing we are near completion',
    ],
    insights: [
      'Public interview format, performed best. Although not likely to be views who will turn into customers, more about top of funnel brand awareness.',
      'Timelapse content showed potential.',
      'TikTok progress was stalled by some content not getting on to the FYP (For You Page) being stuck on 100/200 views.',
    ],
    nextSteps: [
      'Re-edit those videos not posted on tiktok to give them a second chance on tiktok.',
      'Focus on content that advertises the car wash rather than just brand awareness.',
    ],
    igFollowersGrowth: 193,
    igViews: 144000,
    igViewsPctChange: 3704.0,
    igEngagementRate: 3.3,
    ttFollowersGrowth: 218,
    ttViews: 37300,
    ttViewsPctChange: 104.0,
    ttEngagementRate: 4.4,
    posts: [
      {
        id: 'post-s1',
        platform: 'instagram',
        postId: 'ig_post_130k',
        contentFormat: 'Videos',
        viewsCount: 130000,
        likesCount: 5400,
        commentsCount: 349,
        sharesCount: 63,
        thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: true,
        publishedAt: '2026-06-14T11:00:00Z',
      },
      {
        id: 'post-s2',
        platform: 'tiktok',
        postId: 'tt_post_21k',
        contentFormat: 'Videos',
        viewsCount: 21500,
        likesCount: 1630,
        commentsCount: 8,
        sharesCount: 23,
        thumbnailUrl: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: true,
        publishedAt: '2026-06-16T09:00:00Z',
      },
      {
        id: 'post-s3',
        platform: 'tiktok',
        postId: 'tt_post_8k',
        contentFormat: 'Videos',
        viewsCount: 8800,
        likesCount: 1203,
        commentsCount: 15,
        sharesCount: 88,
        thumbnailUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: true,
        publishedAt: '2026-07-02T15:00:00Z',
      },
      {
        id: 'post-s4',
        platform: 'instagram',
        postId: 'ig_post_graphic_safi',
        contentFormat: 'Graphic',
        viewsCount: 6200,
        likesCount: 340,
        commentsCount: 12,
        sharesCount: 18,
        thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
        isTopPerformer: false,
        publishedAt: '2026-06-22T08:00:00Z',
      },
    ],
  },
};
